# Generated by Django 5.2.7 on 2025-12-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('place', models.CharField(verbose_name='Место')),
                ('time', models.CharField(verbose_name='Время')),
                ('action', models.CharField(verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False)),
                ('periodicity', models.IntegerField(default=1, verbose_name='Периодичность(в днях)')),
                ('reward', models.CharField(verbose_name='Награда')),
                ('complete_time', models.DurationField(verbose_name='Время выполнения')),
                ('is_public', models.BooleanField(verbose_name='Публичность')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
