# Generated by Django 5.2.7 on 2025-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefulhabit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
